Repository alinamrmr/homepage, pull requests merged in 2019-05, with the labels that each got.

#3 First release to production
  README.md
  index.html
Labels: release

#8 Update <head> in index.html
  index.html
Labels: enhancement

#9 Patch/content/primary
  asserts/images/Ryurender.png
  index.html
Labels: enhancement

#11 Patch/content/secondary
  asserts/images/Ryurender.png
  index.html
Labels: enhancement

#16 Release to production
  assets/images/Ryurender.png
  index.html
Labels: release

#21 Release to production
  now.json
Labels: release

#22 Update .travis.yml (guess AWS region)
  .travis.yml
Labels: bug, enhancement
